### ISSUE TITLE
Exploração de Dados

### ISSUE THREAD

**Issue by ernandes0** [adiosCarla/avanti-bootcamp-cdd#2]
A equipe deve criar um notebook de análise exploratória ``notebooks/01-exploratory_data_analysis.ipynb``, contendo as seguintes seções de texto:

- [x] **Descrição dos dados:** informações sobre a quantidade de instâncias, variáveis e seus tipos, quantidade de valores faltantes. Utilize o dicionário de dados nessa seção.
- [x] **Perguntas de partida e hipóteses:** que tipo de informações podem ser obtidas a partir dos dados e quais hipóteses podem ser levantadas?
- [x] **Insights:** respostas às perguntas feitas na seção anterior e quais informações interessantes podem ser levantadas através dos dados?

**Comment by fiuzatayna** [comment]
### Coleta inicial de dados e criação do dicionário de dados
 - [x] Adicionou o conjunto de dados na pasta `data/raw/`?
 - [x] Criou e salvou o dicionário de dados na pasta `data/external/`?

### Exploração de dados
Pontos positivos
 - [x] Escreveu uma descrição dos dados?
 - [x] Falou sobre dados faltantes?
 - [x] Escreveu perguntas e partidas de hipóteses?
 - [x] Utilizou mais que 3 tipos de gráficos?
 - [x] Escreveu um sumário dos *insights* no final?
 - [x] Criou gráficos que não foram vistos em aula?
 - [x] Fez análise univariada?
 - [x] Fez análise bivariada?
 - [x] Fez análise multivariada?

Pontos negativos
 - [ ] Usou canal de cor sem necessidade?
 - [ ] Utilizou rótulos inclinados?
 - [ ] Utilizou gráfico de dispersão quando deveria ter utilizado gráfico de boxplot?
 - [ ] Não ordenou gráficos de barra quando deveria?

---
### Comentários
- Executar notebook todo novamente antes de fazer o commit
- Boas perguntas de partida a hipóteses
- Na maioria das células falta texto explicativo sobre o gráfico ou a saída da função executada
- Faltou sumarizar as insights

---
cc @omadson
